name: Build & Upload

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build --no-daemon

      - name: Rename jar to server.jar
        run: |
          mkdir artifacts
          cp target/nukkit-1.0-SNAPSHOT.jar artifacts/server.jar

      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v3
        with:
          name: server-jar
          path: artifacts/server.jar
